apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.lestencrypt.org/directory
    email: 'myemail@google.com'
    privateKeySecretRef: letsencrypt-prod    